"""
Final step: format the canonical Graph (already positioned by the layout
engine) as draw.io-compatible mxGraph XML.

Produces a standard <mxfile><diagram><mxGraphModel> document that imports
cleanly into draw.io / diagrams.net via File > Open, drag-and-drop, or the
"Extract from URL" / paste-XML flows -- no manual fix-up required.
"""
from __future__ import annotations

import html
import time
import uuid
from xml.etree import ElementTree as ET

from ..layout.layered_layout import LayoutResult
from ..models import Graph

CONTAINER_STYLE = (
    "rounded=0;whiteSpace=wrap;html=1;fillColor=none;strokeColor=#999999;"
    "dashed=1;verticalAlign=top;align=left;fontSize=14;fontStyle=1;"
    "fontColor=#666666;spacingLeft=12;spacingTop=8;"
)
TITLE_STYLE = "text;html=1;fontSize=22;fontStyle=1;align=left;verticalAlign=middle;fontColor=#232F3E;"
SUBTITLE_STYLE = "text;html=1;fontSize=11;align=left;verticalAlign=middle;fontColor=#888888;"


def _esc(text) -> str:
    return html.escape(str(text) if text is not None else "", quote=True)


def _edge_style(style: str, bidirectional: bool) -> str:
    parts = [
        "edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;jettySize=auto;",
        "orthogonalLoop=1;fontSize=10;fontColor=#333333;strokeColor=#666666;",
    ]
    if style == "dashed":
        parts.append("dashed=1;")
    if bidirectional:
        parts.append("startArrow=block;startFill=1;endArrow=block;endFill=1;")
    else:
        parts.append("startArrow=none;endArrow=block;endFill=1;")
    return "".join(parts)


def build_drawio_xml(graph: Graph, layout: LayoutResult, generated_by: str = "diagram2drawio") -> str:
    lines: list[str] = []
    lines.append('<?xml version="1.0" encoding="UTF-8"?>')
    lines.append(
        f'<mxfile host="app.diagrams.net" agent="{_esc(generated_by)}" '
        f'modified="{time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())}" version="24.0.0">'
    )
    lines.append(
        f'  <diagram id="{uuid.uuid4()}" name="{_esc(graph.title)}">'
    )
    lines.append(
        f'    <mxGraphModel dx="800" dy="600" grid="1" gridSize="10" guides="1" tooltips="1" '
        f'connect="1" arrows="1" fold="1" page="1" pageScale="1" '
        f'pageWidth="{int(layout.canvas_width)}" pageHeight="{int(layout.canvas_height)}" math="0" shadow="0">'
    )
    lines.append('      <root>')
    lines.append('        <mxCell id="0" />')
    lines.append('        <mxCell id="1" parent="0" />')

    # Title block
    lines.append(
        f'        <mxCell id="title" value="{_esc(graph.title)}" style="{_esc(TITLE_STYLE)}" '
        f'vertex="1" parent="1"><mxGeometry x="40" y="8" width="{int(layout.canvas_width) - 80}" height="30" as="geometry" /></mxCell>'
    )
    lines.append(
        f'        <mxCell id="subtitle" value="Generated by {_esc(generated_by)} &#8226; source: {_esc(graph.source_format)}" '
        f'style="{_esc(SUBTITLE_STYLE)}" vertex="1" parent="1">'
        f'<mxGeometry x="40" y="34" width="{int(layout.canvas_width) - 80}" height="18" as="geometry" /></mxCell>'
    )

    # Containers (architecture layers / explicit source groups)
    for group_id in layout.container_order:
        group = graph.groups[group_id]
        safe_id = f"grp_{group_id}"
        lines.append(
            f'        <mxCell id="{_esc(safe_id)}" value="{_esc(group.label)}" style="{_esc(CONTAINER_STYLE)}" '
            f'vertex="1" parent="1">'
            f'<mxGeometry x="{group.x:.0f}" y="{group.y:.0f}" width="{group.width:.0f}" height="{group.height:.0f}" as="geometry" /></mxCell>'
        )

    # Nodes, parented to their container
    for group_id in layout.container_order:
        group = graph.groups[group_id]
        safe_group_id = f"grp_{group_id}"
        for node_id in group.node_ids:
            node = graph.nodes.get(node_id)
            if node is None:
                continue
            style = node.style or "rounded=1;whiteSpace=wrap;html=1;fillColor=#f5f5f5;strokeColor=#666666;"
            lines.append(
                f'        <mxCell id="{_esc(node.id)}" value="{_esc(node.label)}" style="{_esc(style)}" '
                f'vertex="1" parent="{_esc(safe_group_id)}">'
                f'<mxGeometry x="{node.x:.0f}" y="{node.y:.0f}" width="{node.width:.0f}" height="{node.height:.0f}" as="geometry" /></mxCell>'
            )

    # Edges
    for edge in graph.edges:
        style = _edge_style(edge.style, edge.bidirectional)
        value = f' value="{_esc(edge.label)}"' if edge.label else ''
        lines.append(
            f'        <mxCell id="{_esc(edge.id)}"{value} style="{_esc(style)}" edge="1" '
            f'parent="1" source="{_esc(edge.source)}" target="{_esc(edge.target)}">'
            f'<mxGeometry relative="1" as="geometry" /></mxCell>'
        )

    lines.append('      </root>')
    lines.append('    </mxGraphModel>')
    lines.append('  </diagram>')
    lines.append('</mxfile>')
    xml_text = "\n".join(lines)

    # Validate well-formedness before returning -- fail loudly here rather
    # than producing a .drawio file that draw.io itself will reject.
    ET.fromstring(xml_text)
    return xml_text


def write_drawio_file(graph: Graph, layout: LayoutResult, output_path: str, generated_by: str = "diagram2drawio") -> str:
    xml_text = build_drawio_xml(graph, layout, generated_by=generated_by)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(xml_text)
    return output_path
